services:
  - type: web
    name: skillsprint-api
    runtime: docker
    repo: https://github.com/shivani07-gh/skillsprint
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: 50f38e815ce02691ac2ba1efd759552d22061540f97bc1d41b6f5796eef457cc
        value: 60
      - key: DEBUG
        value: False
      - key: ENVIRONMENT
        value: production
      - key: DB_TYPE
        value: sqlite
      - key: DB_NAME
        value: skillsprint
      - key: DB_ECHO
        value: False
      - key: ALLOWED_ORIGINS
        value: https://skillsprint-api.onrender.com